export const SITE_NAME = 'Best Rome Tours';
export const SITE_CITY = 'Rome';
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.best-rome-tours.com';
export const SITE_DESCRIPTION = 'Discover the best tours, attractions, and experiences in Rome. Book skip-the-line tickets for the Colosseum, Vatican Museums, Sistine Chapel, St Peter’s Basilica, and more with instant confirmation and free cancellation.';
export const GYG_PARTNER_ID = 'LPT26IL';
export const GYG_CAMPAIGN = 'best_rome_tours';
export const GYG_LOCATION_ID = '33';
export const GA_ID = process.env.NEXT_PUBLIC_GA_ID || '';
export const CONTENT_DATE = '2026-07-08';
